version: '3.5'

networks:
    kafka-core_base-net:
        external: true

services:
    ksql-server:
        image: confluentinc/cp-ksql-server:5.4.0
        hostname: ksql-server
        networks:
            - kafka-core_base-net
        ports:
          - "8088:8088"
        environment:
          KSQL_CONFIG_DIR: "/etc/ksql"
          KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
          KSQL_BOOTSTRAP_SERVERS: "broker:29092"
          KSQL_HOST_NAME: ksql-server
          KSQL_LISTENERS: "http://0.0.0.0:8088"
          KSQL_CACHE_MAX_BYTES_BUFFERING: 0
          KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
          KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
          KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
    
    ksql-cli:
        image: confluentinc/cp-ksql-cli:5.4.0
        networks:
            - kafka-core_base-net
        depends_on:
            - ksql-server
        entrypoint: /bin/sh
        tty: true
