version: '3.5'

networks:
    kafka-core_base-net:
        external: true

services:

    mongodb:
        image: 'mongo:3.6.4'
        networks:
            - kafka-core_base-net
        ports:
            - '27017:27017'
        command: mongod --smallfiles --logpath=/dev/null --quiet --replSet rs --wiredTigerCacheSizeGB 1
    
    mongo2:
        image: 'mongo:3.6.4'
        networks:
            - kafka-core_base-net
        command: mongod --smallfiles --logpath=/dev/null --quiet --replSet rs --wiredTigerCacheSizeGB 1

    mongo3:
        image: 'mongo:3.6.4'
        networks:
            - kafka-core_base-net
        command: mongod --smallfiles --logpath=/dev/null --quiet --replSet rs --wiredTigerCacheSizeGB 1

    mongo-seed:
        build: ./mongo
        networks:
            - kafka-core_base-net
        depends_on:
            - mongodb
            - mongo2
            - mongo3

    connect:
        image: confluentinc/cp-kafka-connect:5.4.0
        hostname: connect
        depends_on:
            - mongo-seed
        ports:
            - "8083:8083"
        networks:
            - kafka-core_base-net
        volumes:
            - ./debezium-connector-mongodb:/usr/share/java/debezium-connector-mongodb
        environment:
            CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
            CONNECT_REST_ADVERTISED_HOST_NAME: connect
            CONNECT_REST_PORT: 8083
            CONNECT_GROUP_ID: compose-connect-group
            CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
            CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
            CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
            CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            # CLASSPATH required due to CC-2422
            CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.4.0.jar
            CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
            CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
            CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
            CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR