version: '3.5'

networks:
    base-net:

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.0
        hostname: zookeeper
        networks:
            - base-net
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          
    broker:
        image: confluentinc/cp-kafka:5.4.0
        hostname: broker
        networks:
            - base-net
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
            KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR













































    schema-registry:
        image: confluentinc/cp-schema-registry:5.4.0
        networks:
            - base-net
        hostname: schema-registry
        depends_on:
            - broker
        ports:
            - 8081:8081
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
            SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
        
    rest-proxy:
        image: confluentinc/cp-kafka-rest:5.4.0
        networks:
            - base-net
        depends_on:
            - broker
        ports:
            - 8082:8082
        hostname: rest-proxy
        environment:
            KAFKA_REST_HOST_NAME: rest-proxy
            KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
            KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'

    topics-ui:
        image: landoop/kafka-topics-ui
        networks:
            - base-net
        depends_on:
            - broker
        ports:
            - 8000:8000
        environment:
            KAFKA_REST_PROXY_URL: 'http://rest-proxy:8082'
            PROXY: 'true'


    schema-ui:
        image: landoop/schema-registry-ui
        networks:
            - base-net
        depends_on:
            - schema-registry
        ports:
            - 7000:8000
        environment:
            SCHEMAREGISTRY_URL: 'http://schema-registry:8081'
            PROXY: 'true'